### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Tallyb**
Update readme for correct installation url. 
Removed installation ENV Params that are no longer relevant as installation happens in plugin hook.

### CODE REVIEW

**Comment by codlab** [comment]
the `.git` is unecessary

**Comment by Tallyb** [comment]
Can you please explain how to install, then? It fails for me.

**Comment by bijanmmarkes** [comment]
> the `.git` is unecessary

The .git is in fact necessary. Without it the installation fails.

**Comment by codlab** [comment]
Tested on various environment, the .git id unecessary using the standard https, it's mandatory on git+https (forcing git management protocol) - the above issue is only due to git managing repo signature which changed and requires a full clean from its internal state.

The npmjs bundle should prevent any future burden (as well as the stability from the project from now)

**Pull request closed without merging**
